version: "2"
services:
  nodeRed:
    network_mode: bridge
    image: ghcr.io/iotopen/node-red:3.0.2
    environment:
    - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
    - "ROOT_PATH=/${NAME}"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${NAME}.rule=PathPrefix(`/${NAME}`)"
    - "traefik.http.services.${NAME}.loadbalancer.server.port=1880"
